/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

// Standard library headers
#include <stdio.h>
// Device driver headers
#include "systick.h"
#include "i2c.h"
#include "gpio.h"
// App headers
#include "alarm.h"
#include "game.h"
int main (void)
{
 // Initialize apps
 Init_Alarm();
 Init_Game();
 // Enable services
 StartSysTick();
 while (1) {
 // Run apps
 Task_Alarm();
 Task_Game();
 // Housekeeping
 UpdateIOExpanders();
 ServiceI2CRequests();
 WaitForSysTick();
 }
}
